# Q2. Row Echelon Form:
Create a 5x5 matrix, A, with entries randomly chosen integers between 0 and 9. To generate the
random matrix, set the random seed as the last two digits of your roll number. Reduce matrix A to its
Row Echelon Form by performing elementary row operations

In [3]:
import numpy as np

In [4]:
roll_number = 61 # Replace 61 with your actual last two digits
np.random.seed(roll_number)

In [5]:
A = np.random.randint(0, 10, size=(5, 5))
print("Original matrix A:")
print(A)

Original matrix A:
[[3 2 2 0 2]
 [1 7 5 3 7]
 [0 9 3 4 6]
 [2 3 5 8 2]
 [6 3 2 9 1]]


In [6]:
# Function to perform elementary row operations to reduce to row echelon form
def row_echelon_form(matrix):
    m, n = matrix.shape
    lead = 0
    for r in range(m):
        if lead >= n:
            break
        i = r
        while matrix[i, lead] == 0:
            i += 1
            if i == m:
                i = r
                lead += 1
                if n == lead:
                    break
        matrix[[r, i]] = matrix[[i, r]]
        lv = matrix[r, lead]
        matrix[r] = matrix[r] / lv
        for i in range(m):
            if i != r:
                lv = matrix[i, lead]
                matrix[i] -= lv * matrix[r]
        lead += 1
    return matrix

In [7]:
# Reduce matrix A to its row echelon form
A_row_echelon = row_echelon_form(A)
print("\nRow Echelon Form of matrix A:")
print(A_row_echelon)


Row Echelon Form of matrix A:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
